Net/ThemeName "Yaru-purple-dark"
Net/IconThemeName "Yaru-purple-dark"
Gtk/CursorThemeName "Yaru"
Gtk/FontName "Ubuntu Sans 11"
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/EnablePrimaryPaste 1
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Xft/DPI -1
